// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first terms will be:
// 1,2
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
int fibonacci(int prev, int curr){
    static int sum = 0;
    int new_elem = prev + curr;

    if (new_elem > 4000000)
        return sum;

    if (new_elem%2 == 0)
        sum += new_elem;

    fibonacci(curr, new_elem);

    return sum;
}

int main(){
    std::cout << fibonacci(1,1) << std::endl;;
}